name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.*
    - name: restore-nuget-packages
      run: nuget restore NexiPayout.Framework/NexiPayout.Framework.sln
    - name: Build
      run: dotnet build NexiPayout.Framework/NexiPayout.Framework.sln
    - name: Test
      run: dotnet test --no-build --verbosity normal

